function tangentStiffness = computeSecantTangent( ...
    currentDisplacement, previousDisplacement, currentInternalForce, ...
    previousInternalForce, initialTangentStiffness)
displacementDifference = currentDisplacement - previousDisplacement;

if ~isfinite(displacementDifference) || ...
    abs(displacementDifference) <= eps(max([1, ...
    abs(currentDisplacement), abs(previousDisplacement)]))
    warning('computeSecantTangent:InsufficientDisplacementChange', ...
        ['The secant displacement difference is too small. ', ...
        'Using the initial load-step tangent.']);
    tangentStiffness = initialTangentStiffness;
    return;
end

tangentStiffness = (currentInternalForce - previousInternalForce) / ...
    displacementDifference;
end